### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by ShiroYaksha90** [abenaTenkorang/Capstone_1#2]
Great job so far with implementing your project.

required changes, kindly pay attention to the height of the referenced code and adjusted accordingly the design of the project.
https://github.com/abenaTenkorang/Capstone_1/blob/c70257ba1a608bca8fd4e18e946d9426963d815f/style.css#L104

**Comment by abenaTenkorang** [comment]
Thank you for drawing my attention @ShiroYaksha90.
